/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResumesRouteImport } from './routes/resumes'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ItSystemsRouteImport } from './routes/it-systems'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPlacementInquiryNotifyRouteImport } from './routes/api/public/placement-inquiry-notify'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesRoute = ResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSystemsRoute = ItSystemsRouteImport.update({
  id: '/it-systems',
  path: '/it-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementInquiryNotifyRoute =
  ApiPublicPlacementInquiryNotifyRouteImport.update({
    id: '/api/public/placement-inquiry-notify',
    path: '/api/public/placement-inquiry-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/engineering': typeof EngineeringRoute
  '/it-systems': typeof ItSystemsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/resumes': typeof ResumesRoute
  '/security': typeof SecurityRoute
  '/api/public/placement-inquiry-notify': typeof ApiPublicPlacementInquiryNotifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/engineering': typeof EngineeringRoute
  '/it-systems': typeof ItSystemsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/resumes': typeof ResumesRoute
  '/security': typeof SecurityRoute
  '/api/public/placement-inquiry-notify': typeof ApiPublicPlacementInquiryNotifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/engineering': typeof EngineeringRoute
  '/it-systems': typeof ItSystemsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/resumes': typeof ResumesRoute
  '/security': typeof SecurityRoute
  '/api/public/placement-inquiry-notify': typeof ApiPublicPlacementInquiryNotifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/engineering'
    | '/it-systems'
    | '/privacy-policy'
    | '/refund'
    | '/resumes'
    | '/security'
    | '/api/public/placement-inquiry-notify'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/engineering'
    | '/it-systems'
    | '/privacy-policy'
    | '/refund'
    | '/resumes'
    | '/security'
    | '/api/public/placement-inquiry-notify'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/engineering'
    | '/it-systems'
    | '/privacy-policy'
    | '/refund'
    | '/resumes'
    | '/security'
    | '/api/public/placement-inquiry-notify'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  EngineeringRoute: typeof EngineeringRoute
  ItSystemsRoute: typeof ItSystemsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundRoute: typeof RefundRoute
  ResumesRoute: typeof ResumesRoute
  SecurityRoute: typeof SecurityRoute
  ApiPublicPlacementInquiryNotifyRoute: typeof ApiPublicPlacementInquiryNotifyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes': {
      id: '/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-systems': {
      id: '/it-systems'
      path: '/it-systems'
      fullPath: '/it-systems'
      preLoaderRoute: typeof ItSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement-inquiry-notify': {
      id: '/api/public/placement-inquiry-notify'
      path: '/api/public/placement-inquiry-notify'
      fullPath: '/api/public/placement-inquiry-notify'
      preLoaderRoute: typeof ApiPublicPlacementInquiryNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  EngineeringRoute: EngineeringRoute,
  ItSystemsRoute: ItSystemsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundRoute: RefundRoute,
  ResumesRoute: ResumesRoute,
  SecurityRoute: SecurityRoute,
  ApiPublicPlacementInquiryNotifyRoute: ApiPublicPlacementInquiryNotifyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
